version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-react-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

